### ISSUE TITLE
MAC2 Obsolete Option --ratio

### ISSUE THREAD

**Issue by XuejingLyu** [fndemello/CUT-RUN_greenlist#2]
Hi developers,

**Description of issue:**
I have been referring to your jupyternote book for cut and tag data processing, but when it comes to peak calling step, here's the code from the ipyb:

`macs2 callpeak -t Examples/samples/GSM5956336.bam -c Examples/samples/GSM5956324.bam -n Examples/peaks/Pax3FOXO1-rep1 --ratio ${c} --format BAMPE -g hs --keep-dup all`

I searched for macs2 help manual, as well as forum(https://github.com/macs3-project/MACS/issues/366), the developer of macs2 said they have taken away the `--ratio` option and now it will not have any effect after version 2.2.7.

So I am wondering if the option --ratio still has its effect of using a customized size factor calculated earlier in your pipeline, in taht case how should we know if it's working, and which version of MACS2 were used in your case.

**Command used and output from console**
```
macs2 callpeaks --help
#return:
...
Obsolete options:
  --to-large            Obsolete option. Please use '--scale-to large' instead.
  --ratio RATIO         Obsolete option. Originally designed to normalize treatment and control with customized ratio, now it won't have any effect.
```

Thank you!
Xuejing

**Comment by fndemello** [comment]
Hi Xuejing,

Indeed, the --ratio option was unfortunately made redundant on the newer releases of MACS. For our work we used version 2.1.1.20160309 and confirmed it still worked then. I believe you can still install this deprecated version through their [PyPi](https://pypi.org/project/MACS2/#history), if you'd like.

Another option with the current releases would be to follow their [Advanced Step-by-step tutorial](https://macs3-project.github.io/MACS/docs/Advanced_Step-by-step_Peak_Calling.html), and use Greenlist normalization on step 5, when scaling the samples. But frankly, this advanced tutorial is very laborious, and IMO not worth the trouble.

The easiest option to include Greenlist normalization during peak calling would be to downscale your input bams, either the treatment or IgG, based on Greenlist factors. Downscaling never feels great, but still does the trick.

Otherwise, from our experience the standard peakcalling procedures themselves still hold up fairly well without Greenlist, if they're done properly and with good parameters. The effect of the normalization is most noticeable when performing statistical analyses over the called peaks.

I hope this answer has been helpful!
Best,
Fabio

**Comment by XuejingLyu** [comment]
Hi Fabio,

Thank you for your assistance. The solution you provided worked perfectly. I will close this issue now.

Thanks again for your help!

Best,
Xuejing

**Comment by harish0201** [comment]
Hi,

Thank you for the greenlists and the python notebook. 

I'm planning to use these green-lists and at the step where you calculate the ratio: sample/IgG, using the size-factors. Given that the advanced tutorial seems too much to work around with, I'm planning to go with the downscaling route.

On computing the size factors for my IgG datasets, I get the scaling factors as follows:

|Condition |sizeFactors|in/IgG|
| --------- | ---------- | ---------- |
|Test.in     | 3.21282767 | 1.75772025  
|Ctrl.in     | 2.76970524 | 2.38727905 |
| Ctrl.IgG | 1.16019334 | 1          |
| Test.IgG | 1.82783789 | 1          |


I'm wondering how to use the ratios if they are greater than 1, do I just use all the reads?
